version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASSWORD}'
    ports:
      - '${MYSQL_PORT}:${MYSQL_PORT}'
    expose:
      - '${MYSQL_PORT}'
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql

  mongodb:
    image: mongo:latest
    container_name: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_PASSWORD}'
      MONGO_INITDB_DATABASE: '${MONGO_DATABASE}'
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    expose:
      - '${MONGO_PORT}'
    volumes:
      - ./volumes/mongo-data:/data/db
